name: Google Trends Workflow

on:
  workflow_dispatch:   # Cho phép chạy thủ công
  schedule:
    - cron: "0 0 1 * *"   # Tự động chạy vào ngày 1 mỗi tháng (UTC)

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      run: |
        echo "${GOOGLE_APPLICATION_CREDENTIALS}" > creds.json
        python main.py
