name: Google Trends Workflow

on:
  workflow_dispatch:   # <== phải có để chạy thủ công
  push:
    branches: [ "main" ]

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Write GCP creds to file
        run: echo "${GOOGLE_APPLICATION_CREDENTIALS_JSON}" > creds.json
        env:
          GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}

      - name: Run main.py
        env:
          SHEET_ID: ${{ secrets.SHEET_ID }}
        run: python main.py
