name: Google Trends Workflow

on:
  workflow_dispatch: {}

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      SHEET_ID: ${{ secrets.SHEET_ID }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Ghi nội dung secret JSON ra file creds.json
      - name: Write GCP creds to file
        run: |
          cat > creds.json << 'EOF'
          ${{ secrets.GCP_CREDS }}
          EOF

      # Chạy script
      - name: Run main.py
        run: python main.py
